FROM gcc:15.1.0 as builder
LABEL MAINTAINER=ehemdal@brandeis.edu
RUN mkdir /myapp
COPY ./code/hello.c /myapp
WORKDIR /myapp
RUN gcc -static -o myapp hello.c

FROM alpine:latest
COPY --from=builder /myapp/myapp /myapp
ENTRYPOINT ./myapp
